- name: update trusted ca
  shell: /usr/sbin/update-ca-certificates
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_version'] == "20.04")

- name: restart service.journal
  service:
    name: firewalld
    state: restarted

- name: restart systemd
  ansible.builtin.systemd:
    daemon_reload: yes
